# Generated by Django 4.2.6 on 2023-10-20 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('mat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('synonyms', models.CharField()),
                ('chem_form', models.CharField()),
                ('cas_num', models.IntegerField()),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='Nanoparticle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('np_str', models.CharField()),
                ('size', models.FloatField()),
                ('article_id', models.IntegerField()),
                ('mep_id', models.IntegerField()),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chem.material')),
            ],
            options={
                'db_table': 'nanoparticle',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('surname', models.CharField()),
                ('username', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Synthesis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField()),
                ('article_id', models.IntegerField()),
                ('np', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chem.nanoparticle')),
            ],
            options={
                'db_table': 'synthesis',
            },
        ),
        migrations.CreateModel(
            name='NOVA',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField()),
                ('absorbat', models.CharField()),
                ('pore_size', models.FloatField()),
                ('density', models.FloatField()),
                ('ads_desorb_curve', models.CharField()),
                ('pore_distr_curve', models.CharField()),
                ('np', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chem.nanoparticle')),
            ],
            options={
                'db_table': 'NOVA',
            },
        ),
        migrations.AddField(
            model_name='nanoparticle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chem.user'),
        ),
    ]
