# Generated by Django 4.2.6 on 2023-10-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nanoparticle',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
