# Generated by Django 4.2.6 on 2023-10-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0002_alter_nanoparticle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='mat_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
