# Generated by Django 4.2.6 on 2023-10-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0003_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Nanoparticle',
        ),
        migrations.DeleteModel(
            name='NOVA',
        ),
        migrations.DeleteModel(
            name='Synthesis',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
