# Generated by Django 4.2.6 on 2023-10-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0003_alter_material_mat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nanoparticle',
            name='mat',
        ),
        migrations.RemoveField(
            model_name='nanoparticle',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nova',
            name='np',
        ),
        migrations.RemoveField(
            model_name='synthesis',
            name='np',
        ),
    ]
