# Generated by Django 4.2.6 on 2023-10-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chem', '0004_delete_material_delete_nanoparticle_delete_nova_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('mat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('synonyms', models.CharField()),
                ('chem_form', models.CharField()),
                ('cas_num', models.IntegerField()),
            ],
            options={
                'db_table': 'material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nanoparticle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('np_str', models.CharField()),
                ('size', models.FloatField()),
                ('article_id', models.IntegerField()),
                ('mep_id', models.IntegerField()),
            ],
            options={
                'db_table': 'nanoparticle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NOVA',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField()),
                ('absorbat', models.CharField()),
                ('pore_size', models.FloatField()),
                ('density', models.FloatField()),
                ('ads_desorb_curve', models.CharField()),
                ('pore_distr_curve', models.CharField()),
            ],
            options={
                'db_table': 'NOVA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Synthesis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField()),
                ('article_id', models.IntegerField()),
            ],
            options={
                'db_table': 'synthesis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('surname', models.CharField()),
                ('username', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
