# Generated by Django 4.2.6 on 2023-10-23 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0006_remove_nanoparticle_mat_remove_nanoparticle_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nanoparticle',
            name='mat',
            field=models.ForeignKey(default='MV11207', on_delete=django.db.models.deletion.CASCADE, to='chem.material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nanoparticle',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chem.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nova',
            name='np',
            field=models.ForeignKey(default='MV1130672', on_delete=django.db.models.deletion.CASCADE, to='chem.nanoparticle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='synthesis',
            name='np',
            field=models.ForeignKey(default='MV1130672', on_delete=django.db.models.deletion.CASCADE, to='chem.nanoparticle'),
            preserve_default=False,
        ),
    ]
