# Generated by Django 4.2.6 on 2023-10-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chem', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nanoparticle',
            name='mat_id',
        ),
        migrations.RemoveField(
            model_name='nanoparticle',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='nova',
            name='np_id',
        ),
        migrations.RemoveField(
            model_name='synthesis',
            name='np_id',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Nanoparticle',
        ),
        migrations.DeleteModel(
            name='NOVA',
        ),
        migrations.DeleteModel(
            name='Synthesis',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
